#!/bin/bash

curl -sS https://getcomposer.org/installer | php

sudo apt-get install php5-curl

sudo apt-get install php5-intl

sudo sed -i 's#post_max_size = 8M#post_max_size = 20M#g' /etc/php5/apache2/php.ini

sudo sed -i 's#post_max_size = 8M#post_max_size = 20M#g' /etc/php5/cli/php.ini

echo "ecrire le nom dossier"

read nomdudossier

php composer.phar create-project thelia/thelia-project /var/www/html/$nomdudossier/ 2.2.2
